let graphData=null,renderedGraphData=null,selectedNodeId=null,blastMode=false,currentBlastData=null,currentSearchQuery="",svg,zoomBehavior,zoomLayer,linkLayer,nodeLayer,labelLayer,simulation,linkSelection,nodeSelection,labelSelection,monacoEditor=null,scanFrameTimer=null,isScanning=false,isDraggingDivider=false,blastRequestInFlight=false,graphCacheDbPromise=null,progressiveLoadTimer=null,resizeFrameId=null,currentZoomTransform=d3.zoomIdentity,linkData=[],nodeData=[],themeMode="dark",currentScanTarget="",currentLanguage="python",scanHistory=[],viewMode="split",splitRatio=0.68,layoutMode="tree",clusterMode=true,fullNodeOrder=[],loadedNodeCount=0,currentFocusedClusterKey=null,collapsedClusterKeys=new Set();
const SCAN_HISTORY_STORAGE_KEY="codeweave-scan-history-v1",GRAPH_CACHE_DB_NAME="codeweave-graph-cache",GRAPH_CACHE_STORE="snapshots",VIEW_MODE_STORAGE_KEY="codeweave-view-mode-v1",SPLIT_RATIO_STORAGE_KEY="codeweave-split-ratio-v1",THEME_STORAGE_KEY="codemapper-theme",PROGRESSIVE_THRESHOLD=180,PROGRESSIVE_BATCH_SIZE=120;
const $=(id)=>document.getElementById(id);
function getSelectedNode(){return graphData?.nodes?.find((n)=>n.id===selectedNodeId)||null}
function getRawNode(id){return graphData?.nodes?.find((n)=>n.id===id)||null}
function getTooltipElements(){return{container:$("node-tooltip"),title:$("node-tooltip-title"),body:$("node-tooltip-body")}}
function setMetricValue(id,value){const el=$(id);if(el)el.textContent=value}
function setStatus(message){const el=$("status-label");if(el)el.textContent=message}
function setMode(mode){setMetricValue("metric-mode",mode)}
function setSelectedLabel(label){setMetricValue("metric-selected",label)}
function setGraphMetrics(nodes,edges){setMetricValue("metric-nodes",String(nodes));setMetricValue("metric-edges",String(edges))}
function getThemeColor(name,fallback){return getComputedStyle(document.body).getPropertyValue(name).trim()||fallback}
function getGraphPalette(){return{nodeStroke:getThemeColor("--graph-node-stroke","#111111"),nodeSelected:getThemeColor("--graph-node-selected","#ffcc00"),linkTree:getThemeColor("--graph-link","rgba(149, 193, 214, 0.34)"),linkTreeMuted:getThemeColor("--graph-link-muted","rgba(149, 193, 214, 0.14)"),linkForce:getThemeColor("--graph-link-force","#444444"),label:getThemeColor("--graph-label","#d9e3e8")}}
function truncateLabel(label){label=String(label||"");return label.length>20?`${label.slice(0,17)}...`:label}
function isGithubUrl(value){return /^https?:\/\/(www\.)?github\.com\//i.test(value||"")}
function buildScanHistoryLabel(target){const normalized=String(target||"").trim();if(!normalized)return"Unknown target";if(isGithubUrl(normalized)){try{const url=new URL(normalized);const path=url.pathname.replace(/^\//,"").replace(/\.git$/,"");return path||normalized}catch{return normalized}}const parts=normalized.split(/[\\/]/).filter(Boolean);return parts[parts.length-1]||normalized}
function getClusterKey(node){return node?.file||"Unknown module"}
function getClusterLabel(key){const parts=String(key||"Cluster").split(/[\\/]/).filter(Boolean);return parts[parts.length-1]||key||"Cluster"}
function getNodeRadius(node){if(node.isCluster)return Math.max(18,Math.min(34,16+Math.sqrt(node.memberCount||1)*2.2));const degree=(node.incomingCount||0)+(node.outgoingCount||0);return Math.max(8,Math.min(24,8+degree*1.5))}
function getNodeFill(node){return node.mutation_color||"#7a7a7a"}
function getMonacoTheme(){return themeMode==="light"?"vs":"vs-dark"}
function showEmptyState(){$("graph-empty-state")?.classList.remove("hidden")}
function hideEmptyState(){$("graph-empty-state")?.classList.add("hidden")}
function setScanOverlayMessage(message){const el=$("scan-overlay-copy");if(el)el.textContent=message}
function showScanOverlay(){const overlay=$("scan-overlay");overlay?.classList.add("visible");const frames=["Parsing Python files, linking calls, and preparing the dependency map.","Resolving functions, classes, and import relationships.","Batching summaries and enriching the graph for the UI."];let i=0;setScanOverlayMessage(frames[i]);clearInterval(scanFrameTimer);scanFrameTimer=setInterval(()=>{i=(i+1)%frames.length;setScanOverlayMessage(frames[i])},1200)}
function hideScanOverlay(){$("scan-overlay")?.classList.remove("visible");clearInterval(scanFrameTimer);scanFrameTimer=null}
function applyTheme(nextTheme,persist=true){themeMode=nextTheme;document.body.dataset.theme=nextTheme;const btn=$("theme-toggle-btn");if(btn)btn.textContent=nextTheme==="dark"?"Light Theme":"Dark Theme";if(persist)localStorage.setItem(THEME_STORAGE_KEY,nextTheme)}
function setViewMode(nextMode,persist=true){viewMode=nextMode;const frame=document.querySelector(".main-frame");if(frame){frame.dataset.view=nextMode;if(nextMode==="split")frame.style.gridTemplateColumns=`minmax(0, ${splitRatio}fr) 14px minmax(320px, ${Math.max(0.35,1-splitRatio)}fr)`;else if(nextMode==="graph")frame.style.gridTemplateColumns="1fr 0 0";else frame.style.gridTemplateColumns="0 0 minmax(420px, 1fr)"};$("view-split-btn")?.classList.toggle("active",nextMode==="split");$("view-graph-btn")?.classList.toggle("active",nextMode==="graph");$("view-panel-btn")?.classList.toggle("active",nextMode==="panel");if(persist)localStorage.setItem(VIEW_MODE_STORAGE_KEY,nextMode)}
function loadSplitRatio(){const raw=Number(localStorage.getItem(SPLIT_RATIO_STORAGE_KEY));if(!Number.isNaN(raw)&&raw>=0.35&&raw<=0.82)splitRatio=raw}
function persistSplitRatio(){localStorage.setItem(SPLIT_RATIO_STORAGE_KEY,String(splitRatio))}
function applySplitRatio(){if(viewMode==="split")setViewMode("split",false)}
function setSplitRatioFromPointer(clientX){const frame=document.querySelector(".main-frame");if(!frame)return;const bounds=frame.getBoundingClientRect();splitRatio=Math.min(0.82,Math.max(0.35,(clientX-bounds.left)/bounds.width));persistSplitRatio();applySplitRatio()}
function setDividerDragging(isDragging){isDraggingDivider=isDragging;$("pane-divider")?.classList.toggle("dragging",isDragging);document.body.style.userSelect=isDragging?"none":""}
function openGraphCacheDb(){if(graphCacheDbPromise)return graphCacheDbPromise;graphCacheDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(GRAPH_CACHE_DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(GRAPH_CACHE_STORE))db.createObjectStore(GRAPH_CACHE_STORE,{keyPath:"target"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return graphCacheDbPromise}
async function saveGraphSnapshot(target,data){if(!target||!data)return;try{const db=await openGraphCacheDb();await new Promise((resolve,reject)=>{const tx=db.transaction(GRAPH_CACHE_STORE,"readwrite");tx.objectStore(GRAPH_CACHE_STORE).put({target,data,updatedAt:Date.now()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch(error){console.error(error)}}
async function getGraphSnapshot(target){if(!target)return null;try{const db=await openGraphCacheDb();return await new Promise((resolve,reject)=>{const req=db.transaction(GRAPH_CACHE_STORE,"readonly").objectStore(GRAPH_CACHE_STORE).get(target);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}catch(error){console.error(error);return null}}
async function loadLanguageOptions(){const select=$("language-input");if(!select)return;try{const response=await fetch("/api/languages"),data=await response.json();if(!response.ok||!Array.isArray(data.languages))return;select.innerHTML="";data.languages.forEach((item)=>{const option=document.createElement("option");option.value=String(item.language||"python");option.textContent=item.ready===false?`${item.label} (stub)` : item.label;select.appendChild(option)});select.value=currentLanguage}catch(error){console.error(error)}}
function persistLocalList(key,value){localStorage.setItem(key,JSON.stringify(value))}
function loadLocalList(key){try{const raw=localStorage.getItem(key);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch(error){console.error(error);return[]}}
function loadScanHistory(){scanHistory=loadLocalList(SCAN_HISTORY_STORAGE_KEY)}
function persistScanHistory(){persistLocalList(SCAN_HISTORY_STORAGE_KEY,scanHistory)}
function renderScanHistory(){const c=$("scan-history-list");if(!c)return;c.innerHTML="";if(!scanHistory.length){const e=document.createElement("div");e.className="scan-history-empty";e.textContent="Scanned project paths and GitHub repos will appear here.";c.appendChild(e);return}scanHistory.forEach((entry)=>{const b=document.createElement("button");b.className=`scan-history-chip ${entry.target===currentScanTarget?"active":""}`;b.innerHTML=`<span class="scan-history-chip-inner"><span class="scan-history-kind">${entry.kind}</span><span class="scan-history-label">${entry.label}</span></span><span class="chip-delete-btn" title="Remove from recent scans">x</span>`;b.title=entry.target;b.addEventListener("click",async(event)=>{if(event.target instanceof HTMLElement&&event.target.classList.contains("chip-delete-btn")){event.stopPropagation();deleteScanHistoryEntry(entry.target);return}$("path-input").value=entry.target;currentScanTarget=entry.target;renderScanHistory();const loaded=await loadCachedScanTarget(entry.target,{silent:true});setStatus(loaded?`Loaded cached graph for ${entry.target}`:`Loaded recent target: ${entry.target}`)});c.appendChild(b)})}
function addScanHistoryEntry(target){const normalized=String(target||"").trim();if(!normalized)return;currentScanTarget=normalized;const entry={target:normalized,label:buildScanHistoryLabel(normalized),kind:isGithubUrl(normalized)?"GitHub":"Local",updatedAt:Date.now()};scanHistory=[entry,...scanHistory.filter((i)=>i.target!==normalized)].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,12);persistScanHistory();renderScanHistory()}
function clearScanHistory(){scanHistory=[];currentScanTarget="";localStorage.removeItem(SCAN_HISTORY_STORAGE_KEY);renderScanHistory();setStatus("Cleared recent scan history.")}
function deleteScanHistoryEntry(target){scanHistory=scanHistory.filter((e)=>e.target!==target);if(currentScanTarget===target)currentScanTarget="";persistScanHistory();renderScanHistory();setStatus(`Removed recent scan: ${target}`)}
async function loadCachedScanTarget(target,options={}){const normalized=String(target||"").trim();if(!normalized)return false;const snapshot=await getGraphSnapshot(normalized);if(!snapshot?.data)return false;currentScanTarget=normalized;window.__CODEWEAVE_SCAN_TARGET__=normalized;updateGraph(snapshot.data);if(!options.silent)setStatus(`Loaded cached graph for ${normalized}`);renderScanHistory();return true}
function syncActionButtons(){const hasSelection=Boolean(getSelectedNode());$("simulate-blast-btn").disabled=!hasSelection||blastRequestInFlight;$("simulate-blast-btn").textContent=blastRequestInFlight?"Running Blast...":"Simulate Blast Radius";$("view-source-btn").disabled=!hasSelection;$("cluster-toggle-btn")?.classList.toggle("active",clusterMode);$("tree-layout-btn")?.classList.toggle("active",layoutMode==="tree");$("force-layout-btn")?.classList.toggle("active",layoutMode==="force")}
function computeNodeDegrees(data){const degreeMap=new Map();data.nodes.forEach((node)=>degreeMap.set(node.id,{incoming:0,outgoing:0}));data.edges.forEach((edge)=>{if(degreeMap.has(edge.source))degreeMap.get(edge.source).outgoing+=1;if(degreeMap.has(edge.target))degreeMap.get(edge.target).incoming+=1});data.nodes.forEach((node)=>{const counts=degreeMap.get(node.id)||{incoming:0,outgoing:0};node.incomingCount=counts.incoming;node.outgoingCount=counts.outgoing});fullNodeOrder=data.nodes.slice().sort((a,b)=>((b.incomingCount||0)+(b.outgoingCount||0))-((a.incomingCount||0)+(a.outgoingCount||0))||a.name.localeCompare(b.name))}
function initializeCollapsedClusters(){if(!graphData){collapsedClusterKeys=new Set();return}const grouped=new Map();graphData.nodes.forEach((node)=>{const key=getClusterKey(node);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(node)});collapsedClusterKeys=new Set([...grouped.entries()].filter(([,nodes])=>nodes.length>=4).map(([key])=>key))}
function getVisibleBaseNodes(){if(!graphData)return[];if(graphData.nodes.length<=PROGRESSIVE_THRESHOLD)loadedNodeCount=graphData.nodes.length;return fullNodeOrder.slice(0,Math.max(0,Math.min(loadedNodeCount||graphData.nodes.length,graphData.nodes.length)))}
function getVisibleBaseGraph(){const visibleNodes=getVisibleBaseNodes();const ids=new Set(visibleNodes.map((node)=>node.id));return{nodes:visibleNodes,edges:graphData.edges.filter((edge)=>ids.has(edge.source)&&ids.has(edge.target))}}
function deriveClusterColor(nodes){const states=nodes.map((node)=>(node.mutation_status||"stable").toLowerCase());if(states.includes("hotspot"))return"#ff4444";if(states.includes("new"))return"#00ff88";if(states.includes("modified"))return"#ffcc00";return"#aaaaaa"}
function buildDisplayGraphData(){if(!graphData)return{nodes:[],edges:[]};const visibleBase=getVisibleBaseGraph();if(!clusterMode)return{nodes:visibleBase.nodes.map((node)=>({...node})),edges:visibleBase.edges.map((edge)=>({...edge}))};const grouped=new Map(),displayNodes=[],nodeToDisplay=new Map();visibleBase.nodes.forEach((node)=>{const key=getClusterKey(node);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(node)});grouped.forEach((nodes,clusterKey)=>{const collapse=collapsedClusterKeys.has(clusterKey)&&nodes.length>1;if(collapse){const displayId=`cluster::${clusterKey}`;const aggregate=nodes.reduce((sum,node)=>sum+(node.incomingCount||0)+(node.outgoingCount||0),0);displayNodes.push({id:displayId,name:getClusterLabel(clusterKey),type:"cluster",file:clusterKey,line:0,args:[],source_code:"",summary:`${nodes.length} nodes collapsed. Click to expand this file cluster.`,memberCount:nodes.length,memberIds:nodes.map((node)=>node.id),isCluster:true,clusterKey,mutation_color:deriveClusterColor(nodes),incomingCount:aggregate,outgoingCount:aggregate});nodes.forEach((node)=>nodeToDisplay.set(node.id,displayId))}else{nodes.forEach((node)=>{displayNodes.push({...node,clusterKey,isCluster:false});nodeToDisplay.set(node.id,node.id)})}});const edges=new Map();visibleBase.edges.forEach((edge)=>{const source=nodeToDisplay.get(edge.source),target=nodeToDisplay.get(edge.target);if(!source||!target||source===target)return;const key=`${source}::${target}`;if(!edges.has(key))edges.set(key,{source,target,weight:0});edges.get(key).weight+=1});return{nodes:displayNodes,edges:[...edges.values()]}}
function updateGraphProgress(){const pill=$("graph-progress-pill"),visible=graphData?Math.min(loadedNodeCount,graphData.nodes.length):0,total=graphData?.nodes?.length||0;if(pill)pill.innerHTML=`Visible<strong>${visible} / ${total}</strong>`;const hasMore=total>visible;$("graph-load-more-btn").disabled=!hasMore;$("graph-show-all-btn").disabled=!hasMore}
function renderBreadcrumbs(){const c=$("graph-breadcrumbs");if(!c)return;c.innerHTML="";if(!currentScanTarget&&!selectedNodeId&&!currentFocusedClusterKey)return;const crumbs=[];if(currentScanTarget)crumbs.push({label:buildScanHistoryLabel(currentScanTarget),onClick:()=>{selectedNodeId=null;currentFocusedClusterKey=null;restoreVisualState()}});if(currentFocusedClusterKey)crumbs.push({label:getClusterLabel(currentFocusedClusterKey),onClick:()=>{collapsedClusterKeys.delete(currentFocusedClusterKey);renderGraph(graphData);restoreVisualState()}});if(selectedNodeId){const node=getSelectedNode();if(node)crumbs.push({label:node.name,onClick:()=>highlightNode(node.id)})}crumbs.forEach((crumb,index)=>{const b=document.createElement("button");b.className="breadcrumb-chip";b.textContent=crumb.label;b.addEventListener("click",crumb.onClick);c.appendChild(b);if(index<crumbs.length-1){const s=document.createElement("span");s.className="breadcrumb-sep";s.textContent=">";c.appendChild(s)}})}
function buildSvgShell(){svg=d3.select("#graph-svg");svg.selectAll("*").remove();const defs=svg.append("defs");defs.append("marker").attr("id","arrowhead").attr("viewBox","0 -5 10 10").attr("refX",22).attr("refY",0).attr("markerWidth",7).attr("markerHeight",7).attr("orient","auto").append("path").attr("d","M0,-5L10,0L0,5").attr("fill","#666");zoomLayer=svg.append("g").attr("class","zoom-layer");linkLayer=zoomLayer.append("g").attr("class","links");nodeLayer=zoomLayer.append("g").attr("class","nodes");labelLayer=zoomLayer.append("g").attr("class","labels");zoomBehavior=d3.zoom().scaleExtent([0.2,3]).on("start",()=>{hideNodeTooltip();if(labelSelection)labelSelection.attr("display","none")}).on("zoom",(event)=>{currentZoomTransform=event.transform;zoomLayer.attr("transform",currentZoomTransform)}).on("end",()=>{if(labelSelection)labelSelection.attr("display",null);restoreVisualState()});svg.call(zoomBehavior);svg.call(zoomBehavior.transform,currentZoomTransform)}
function buildGraphCollections(data){nodeData=data.nodes.map((node)=>({...node}));const byId=new Map(nodeData.map((node)=>[node.id,node]));linkData=data.edges.map((edge)=>({...edge,source:byId.get(edge.source),target:byId.get(edge.target)})).filter((edge)=>edge.source&&edge.target);return{nodes:nodeData,links:linkData}}
function applyTreeLayout(nodes,links,width,height){const incoming=new Map(nodes.map((node)=>[node.id,[]])),outgoing=new Map(nodes.map((node)=>[node.id,[]]));links.forEach((link)=>{incoming.get(link.target.id)?.push(link.source.id);outgoing.get(link.source.id)?.push(link.target.id)});let roots=nodes.filter((node)=>(incoming.get(node.id)||[]).length===0);if(!roots.length&&nodes.length)roots=[...nodes].sort((a,b)=>(b.outgoingCount||0)-(a.outgoingCount||0)).slice(0,1);const depthMap=new Map(),queue=roots.map((node)=>({id:node.id,depth:0}));while(queue.length){const current=queue.shift();if(depthMap.has(current.id))continue;depthMap.set(current.id,current.depth);(outgoing.get(current.id)||[]).forEach((childId)=>{if(!depthMap.has(childId))queue.push({id:childId,depth:current.depth+1})})}let fallback=depthMap.size?Math.max(...depthMap.values())+1:0;nodes.forEach((node)=>{if(!depthMap.has(node.id)){depthMap.set(node.id,fallback);fallback+=1}});const layers=new Map();nodes.forEach((node)=>{const depth=depthMap.get(node.id)||0;if(!layers.has(depth))layers.set(depth,[]);layers.get(depth).push(node)});const ordered=[...layers.keys()].sort((a,b)=>a-b),left=110,right=140,top=110,bottom=90,xStep=ordered.length>1?(width-left-right)/(ordered.length-1):0;ordered.forEach((depth)=>{const layer=layers.get(depth).sort((a,b)=>((b.outgoingCount||0)+(b.incomingCount||0))-((a.outgoingCount||0)+(a.incomingCount||0)));const yStep=layer.length>1?(height-top-bottom)/(layer.length-1):0;layer.forEach((node,index)=>{node.x=left+depth*xStep;node.y=layer.length===1?height/2:top+index*yStep})})}
function treePath(link){const midX=(link.source.x+link.target.x)/2;return`M${link.source.x},${link.source.y} C${midX},${link.source.y} ${midX},${link.target.y} ${link.target.x},${link.target.y}`}
function showNodeTooltip(node,event){const{container,title,body}=getTooltipElements();if(!container||!title||!body)return;title.textContent=node.isCluster?`${node.name} cluster`:(node.name||"Node");body.textContent=node.summary||"No summary available.";container.classList.add("visible");moveNodeTooltip(event)}
function moveNodeTooltip(event){const{container}=getTooltipElements(),graphContainer=$("graph-container");if(!container||!graphContainer)return;const bounds=graphContainer.getBoundingClientRect(),tooltipWidth=container.offsetWidth||280,tooltipHeight=container.offsetHeight||80;let left=event.clientX-bounds.left+18,top=event.clientY-bounds.top+18;if(left+tooltipWidth>bounds.width-12)left=bounds.width-tooltipWidth-12;if(top+tooltipHeight>bounds.height-12)top=bounds.height-tooltipHeight-12;container.style.left=`${Math.max(12,left)}px`;container.style.top=`${Math.max(12,top)}px`}
function hideNodeTooltip(){getTooltipElements().container?.classList.remove("visible")}
function ensureNodeVisibleAndExpanded(nodeId){const raw=getRawNode(nodeId);if(!raw)return false;let changed=false;if(loadedNodeCount<graphData.nodes.length){const visibleIds=new Set(getVisibleBaseNodes().map((node)=>node.id));if(!visibleIds.has(nodeId)){loadedNodeCount=graphData.nodes.length;changed=true}}const clusterKey=getClusterKey(raw);if(collapsedClusterKeys.has(clusterKey)){collapsedClusterKeys.delete(clusterKey);changed=true}currentFocusedClusterKey=clusterKey;return changed}
function handleNodePrimaryAction(node){if(node.isCluster){collapsedClusterKeys.delete(node.clusterKey);currentFocusedClusterKey=node.clusterKey;renderGraph(graphData);restoreVisualState();setStatus(`Expanded ${node.name} cluster.`);return}selectNode(node.id,true)}
function bindNodeInteractions(selection){selection.style("cursor","pointer").on("click",(_,node)=>handleNodePrimaryAction(node)).on("mouseenter",(event,node)=>{showNodeTooltip(node,event);applyHoverTrace(node.id)}).on("mousemove",(event)=>moveNodeTooltip(event)).on("mouseleave",()=>{hideNodeTooltip();restoreVisualState()}).on("contextmenu",(event,node)=>{if(node.isCluster)return;event.preventDefault();triggerBlastRadius(node)}).on("dblclick",(_,node)=>{if(node.isCluster){handleNodePrimaryAction(node);return}openMonacoModal(node.source_code||"# No source code available")})}
function renderTreeGraph(data,width,height){const{nodes,links}=buildGraphCollections(data),palette=getGraphPalette();applyTreeLayout(nodes,links,width,height);linkSelection=linkLayer.selectAll("path").data(links,(link)=>`${link.source.id}-${link.target.id}`).join("path").attr("d",(link)=>treePath(link)).attr("fill","none").attr("stroke",palette.linkTree).attr("stroke-width",(link)=>Math.min(3,1.1+(link.weight||1)*0.2)).attr("marker-end","url(#arrowhead)");nodeSelection=nodeLayer.selectAll("circle").data(nodes,(node)=>node.id).join("circle").attr("cx",(node)=>node.x).attr("cy",(node)=>node.y).attr("r",(node)=>getNodeRadius(node)).attr("fill",(node)=>getNodeFill(node)).attr("stroke",palette.nodeStroke).attr("stroke-width",2).attr("data-node-id",(node)=>node.id);bindNodeInteractions(nodeSelection);labelSelection=labelLayer.selectAll("text").data(nodes,(node)=>node.id).join("text").text((node)=>node.isCluster?`${truncateLabel(node.name)} (${node.memberCount})`:truncateLabel(node.name)).attr("x",(node)=>node.x+getNodeRadius(node)+10).attr("y",(node)=>node.y+4).attr("fill",palette.label).attr("font-size",(node)=>node.isCluster?12.5:12).attr("font-weight",(node)=>node.isCluster?700:500).attr("text-anchor","start").attr("pointer-events","none")}
function renderForceGraph(data,width,height){const{nodes,links}=buildGraphCollections(data),palette=getGraphPalette();simulation=d3.forceSimulation(nodes).force("link",d3.forceLink(links).id((node)=>node.id).distance((link)=>link.source.isCluster||link.target.isCluster?160:120)).force("charge",d3.forceManyBody().strength((node)=>node.isCluster?-520:-300)).force("center",d3.forceCenter(width/2,height/2)).force("collide",d3.forceCollide().radius((node)=>getNodeRadius(node)+12)).alphaDecay(0.08).velocityDecay(0.45);linkSelection=linkLayer.selectAll("line").data(links,(link)=>`${link.source.id}-${link.target.id}`).join("line").attr("stroke",palette.linkForce).attr("stroke-width",(link)=>Math.min(3,1+(link.weight||1)*0.16)).attr("marker-end","url(#arrowhead)");nodeSelection=nodeLayer.selectAll("circle").data(nodes,(node)=>node.id).join("circle").attr("r",(node)=>getNodeRadius(node)).attr("fill",(node)=>getNodeFill(node)).attr("stroke",palette.nodeStroke).attr("stroke-width",2).attr("data-node-id",(node)=>node.id).call(d3.drag().on("start",dragStarted).on("drag",dragged).on("end",dragEnded));bindNodeInteractions(nodeSelection);labelSelection=labelLayer.selectAll("text").data(nodes,(node)=>node.id).join("text").text((node)=>node.isCluster?`${truncateLabel(node.name)} (${node.memberCount})`:truncateLabel(node.name)).attr("fill",palette.label).attr("font-size",(node)=>node.isCluster?12.5:12).attr("font-weight",(node)=>node.isCluster?700:500).attr("text-anchor","middle").attr("pointer-events","none");simulation.on("tick",()=>{linkSelection.attr("x1",(link)=>link.source.x).attr("y1",(link)=>link.source.y).attr("x2",(link)=>link.target.x).attr("y2",(link)=>link.target.y);nodeSelection.attr("cx",(node)=>node.x).attr("cy",(node)=>node.y);labelSelection.attr("x",(node)=>node.x).attr("y",(node)=>node.y+getNodeRadius(node)+14)})}
function renderGraph(data){const container=$("graph-container");if(!container||!data)return;const width=container.clientWidth,height=container.clientHeight;renderedGraphData=buildDisplayGraphData();buildSvgShell();if(simulation){simulation.stop();simulation=null}if(layoutMode==="tree")renderTreeGraph(renderedGraphData,width,height);else renderForceGraph(renderedGraphData,width,height);updateGraphProgress();renderBreadcrumbs()}
function dragStarted(event){if(!simulation)return;if(!event.active)simulation.alphaTarget(0.3).restart();event.subject.fx=event.subject.x;event.subject.fy=event.subject.y}
function dragged(event){event.subject.fx=event.x;event.subject.fy=event.y}
function dragEnded(event){if(!simulation)return;if(!event.active)simulation.alphaTarget(0);event.subject.fx=null;event.subject.fy=null}
function stopProgressiveLoading(){if(progressiveLoadTimer){clearTimeout(progressiveLoadTimer);progressiveLoadTimer=null}}
function startProgressiveLoading(){stopProgressiveLoading();if(!graphData||loadedNodeCount>=graphData.nodes.length){updateGraphProgress();return}progressiveLoadTimer=setTimeout(()=>{loadedNodeCount=Math.min(graphData.nodes.length,loadedNodeCount+PROGRESSIVE_BATCH_SIZE);renderGraph(graphData);restoreVisualState();if(loadedNodeCount<graphData.nodes.length)startProgressiveLoading();else setStatus(`Loaded ${graphData.nodes.length} nodes and ${graphData.edges.length} edges`)},160)}
function setLayoutMode(nextMode){layoutMode=nextMode;if(graphData){renderGraph(graphData);restoreVisualState()}syncActionButtons()}
function setClusterMode(nextValue){clusterMode=nextValue;if(graphData){renderGraph(graphData);restoreVisualState()}syncActionButtons()}
function applyBaseGraphStyle(){if(!nodeSelection||!labelSelection||!linkSelection)return;const palette=getGraphPalette();nodeSelection.classed("epicenter",false).attr("fill",(node)=>getNodeFill(node)).attr("opacity",1).attr("stroke",(node)=>node.id===selectedNodeId?palette.nodeSelected:palette.nodeStroke).attr("stroke-width",(node)=>node.id===selectedNodeId?4:2);labelSelection.attr("opacity",1);linkSelection.attr("opacity",layoutMode==="tree"?0.78:0.72).attr("stroke",layoutMode==="tree"?palette.linkTree:palette.linkForce)}
function collectReachable(startId,direction){if(!renderedGraphData)return new Set();const adj=new Map();renderedGraphData.nodes.forEach((node)=>adj.set(node.id,[]));renderedGraphData.edges.forEach((edge)=>{const from=direction==="out"?edge.source:edge.target,to=direction==="out"?edge.target:edge.source;adj.get(from)?.push(to)});const visited=new Set(),queue=[startId];while(queue.length){const current=queue.shift();(adj.get(current)||[]).forEach((neighbor)=>{if(!visited.has(neighbor)&&neighbor!==startId){visited.add(neighbor);queue.push(neighbor)}})}return visited}
function applyHoverTrace(nodeId){if(!nodeSelection||blastMode||currentSearchQuery.trim())return;const palette=getGraphPalette(),outgoing=collectReachable(nodeId,"out"),incoming=collectReachable(nodeId,"in"),activeNodes=new Set([nodeId,...outgoing,...incoming]);nodeSelection.attr("opacity",(node)=>activeNodes.has(node.id)?1:0.14).attr("stroke",(node)=>node.id===nodeId?palette.nodeSelected:incoming.has(node.id)?"#66d7d1":outgoing.has(node.id)?"#ffb65c":palette.nodeStroke).attr("stroke-width",(node)=>node.id===nodeId?4:activeNodes.has(node.id)?3:1.6);labelSelection.attr("opacity",(node)=>activeNodes.has(node.id)?1:0.18);linkSelection.attr("opacity",(link)=>{const forward=(link.source.id===nodeId||outgoing.has(link.source.id))&&(outgoing.has(link.target.id)||link.target.id===nodeId),reverse=(link.target.id===nodeId||incoming.has(link.target.id))&&(incoming.has(link.source.id)||link.source.id===nodeId);return forward||reverse?0.96:0.06}).attr("stroke",(link)=>{const forward=(link.source.id===nodeId||outgoing.has(link.source.id))&&(outgoing.has(link.target.id)||link.target.id===nodeId),reverse=(link.target.id===nodeId||incoming.has(link.target.id))&&(incoming.has(link.source.id)||link.source.id===nodeId);if(forward)return"#ffb65c";if(reverse)return"#66d7d1";return layoutMode==="tree"?palette.linkTreeMuted:palette.linkForce})}
function highlightNode(nodeId){if(!graphData)return;const changed=ensureNodeVisibleAndExpanded(nodeId);if(changed)renderGraph(graphData);selectedNodeId=nodeId;const selected=getSelectedNode();if(selected)currentFocusedClusterKey=getClusterKey(selected);setSelectedLabel(selected?selected.name:"None");renderBreadcrumbs();syncActionButtons();restoreVisualState()}
function selectNode(nodeId,openDetail=false){highlightNode(nodeId);if(openDetail){const raw=getRawNode(nodeId);if(raw&&window.loadNodeDetail)window.loadNodeDetail(raw,graphData)}}
function applyBlastData(data){if(!data||!nodeSelection)return;const palette=getGraphPalette();blastMode=true;currentBlastData=data;setMode("Blast");const affected=new Set(data.affected_nodes||[]);nodeSelection.classed("epicenter",(node)=>node.id===data.epicenter).attr("fill",(node)=>data.risk_colors?.[node.id]||getNodeFill(node)).attr("opacity",(node)=>affected.has(node.id)?1:0.12).attr("stroke",(node)=>node.id===data.epicenter?"#fff5d6":node.id===selectedNodeId?palette.nodeSelected:palette.nodeStroke);labelSelection.attr("opacity",(node)=>affected.has(node.id)?1:0.14);linkSelection.attr("opacity",(link)=>affected.has(link.source.id)&&affected.has(link.target.id)?0.95:0.05).attr("stroke",(link)=>affected.has(link.source.id)&&affected.has(link.target.id)?"rgba(255, 190, 137, 0.65)":layoutMode==="tree"?palette.linkTreeMuted:palette.linkForce);if(window.showBlastInfo)window.showBlastInfo(data)}
async function triggerBlastRadius(node){if(!node||node.isCluster||blastRequestInFlight)return;try{blastRequestInFlight=true;syncActionButtons();setStatus(`Simulating blast radius for ${node.name}...`);const response=await fetch(`/api/blast/${node.id}`),data=await response.json();if(!response.ok)throw new Error(data.error||"Blast radius failed");applyBlastData(data);setStatus(data.summary)}catch(error){console.error(error);setStatus(error.message)}finally{blastRequestInFlight=false;syncActionButtons()}}
function clearBlastRadius(){blastMode=false;currentBlastData=null;setMode("Explore");applyBaseGraphStyle();if(window.showBlastInfo)window.showBlastInfo({summary:"Right-click a node to simulate impact.",depth_map:{}});if(currentSearchQuery)searchNodes(currentSearchQuery);syncActionButtons()}
function searchNodes(query){currentSearchQuery=String(query||"").trim();if(!graphData||!nodeSelection)return;if(!currentSearchQuery){applyBaseGraphStyle();if(blastMode&&currentBlastData)applyBlastData(currentBlastData);setStatus(graphData?`Loaded ${graphData.nodes.length} nodes and ${graphData.edges.length} edges`:"Ready to scan");return}const normalized=currentSearchQuery.toLowerCase(),matchingRawIds=new Set(graphData.nodes.filter((node)=>node.name.toLowerCase().includes(normalized)||(node.summary||"").toLowerCase().includes(normalized)).map((node)=>node.id)),matchingDisplayIds=new Set();renderedGraphData.nodes.forEach((node)=>{if(node.isCluster){if((node.memberIds||[]).some((id)=>matchingRawIds.has(id)))matchingDisplayIds.add(node.id)}else if(matchingRawIds.has(node.id))matchingDisplayIds.add(node.id)});const palette=getGraphPalette();nodeSelection.attr("opacity",(node)=>matchingDisplayIds.has(node.id)?1:0.18).attr("stroke",(node)=>matchingDisplayIds.has(node.id)?palette.nodeSelected:palette.nodeStroke).attr("stroke-width",(node)=>matchingDisplayIds.has(node.id)?4:2);labelSelection.attr("opacity",(node)=>matchingDisplayIds.has(node.id)?1:0.2);linkSelection.attr("opacity",(link)=>matchingDisplayIds.has(link.source.id)||matchingDisplayIds.has(link.target.id)?0.85:0.06);setStatus(`Search matched ${matchingRawIds.size} node${matchingRawIds.size===1?"":"s"}`)}
function restoreVisualState(){applyBaseGraphStyle();if(blastMode&&currentBlastData)applyBlastData(currentBlastData);else if(currentSearchQuery)searchNodes(currentSearchQuery)}
function ensureMonaco(sourceCode){return new Promise((resolve)=>{if(monacoEditor&&window.monaco){monacoEditor.setValue(sourceCode);resolve();return}window.require.config({paths:{vs:"https://cdn.jsdelivr.net/npm/monaco-editor@0.44.0/min/vs"}});window.require(["vs/editor/editor.main"],()=>{monacoEditor=window.monaco.editor.create($("monaco-editor"),{value:sourceCode,language:"python",readOnly:true,theme:getMonacoTheme(),minimap:{enabled:false},fontSize:14});resolve()})})}
async function openMonacoModal(source){$("monaco-modal").classList.add("visible");await ensureMonaco(source);monacoEditor?.layout()}
function serializeSvg(){const source=new XMLSerializer().serializeToString($("graph-svg"));return source.includes("xmlns=")?source:source.replace("<svg",'<svg xmlns="http://www.w3.org/2000/svg"')}
function downloadBlob(filename,type,payload){const blob=payload instanceof Blob?payload:new Blob([payload],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportGraphSvg(){downloadBlob(`${buildScanHistoryLabel(currentScanTarget||"graph")}.svg`,"image/svg+xml;charset=utf-8",serializeSvg());setStatus("Exported SVG snapshot.")}
async function exportGraphPng(){try{const svgMarkup=serializeSvg(),url=URL.createObjectURL(new Blob([svgMarkup],{type:"image/svg+xml;charset=utf-8"})),image=new Image(),container=$("graph-container");image.onload=()=>{const canvas=document.createElement("canvas");canvas.width=container.clientWidth*devicePixelRatio;canvas.height=container.clientHeight*devicePixelRatio;const ctx=canvas.getContext("2d");ctx.scale(devicePixelRatio,devicePixelRatio);ctx.fillStyle=themeMode==="light"?"#eef4f7":"#0d0d0d";ctx.fillRect(0,0,container.clientWidth,container.clientHeight);ctx.drawImage(image,0,0,container.clientWidth,container.clientHeight);canvas.toBlob((blob)=>{downloadBlob(`${buildScanHistoryLabel(currentScanTarget||"graph")}.png`,"image/png",blob);URL.revokeObjectURL(url);setStatus("Exported PNG snapshot.")})};image.src=url}catch(error){console.error(error);setStatus("Could not export PNG snapshot.")}}
function exportGraphJson(){downloadBlob(`${buildScanHistoryLabel(currentScanTarget||"graph")}.json`,"application/json;charset=utf-8",JSON.stringify({graph:graphData},null,2));setStatus("Exported JSON snapshot.")}
function scheduleGraphResize(){if(!graphData)return;if(resizeFrameId){cancelAnimationFrame(resizeFrameId)}resizeFrameId=requestAnimationFrame(()=>{renderGraph(graphData);restoreVisualState();resizeFrameId=null})}
function loadMoreNodes(){if(!graphData)return;loadedNodeCount=Math.min(graphData.nodes.length,loadedNodeCount+PROGRESSIVE_BATCH_SIZE);renderGraph(graphData);restoreVisualState();startProgressiveLoading()}
function showAllNodes(){if(!graphData)return;loadedNodeCount=graphData.nodes.length;stopProgressiveLoading();renderGraph(graphData);restoreVisualState();setStatus(`Loaded all ${graphData.nodes.length} nodes.`)}
async function scanProject(){if(isScanning)return;const path=$("path-input").value.trim();currentLanguage=$("language-input")?.value?.trim()||"python";if(!path){setStatus("Enter an absolute project path or GitHub repository URL.");return}try{isScanning=true;setStatus(`Scanning ${currentLanguage} project...`);setMode("Scan");showScanOverlay();const response=await fetch("/api/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path,language:currentLanguage})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Scan failed");currentScanTarget=path;window.__CODEWEAVE_SCAN_TARGET__=path;updateGraph(data);addScanHistoryEntry(path);await saveGraphSnapshot(path,data);setStatus(`Loaded ${data.nodes.length} nodes and ${data.edges.length} edges (${currentLanguage})`)}catch(error){console.error(error);setStatus(error.message);setMode("Error")}finally{isScanning=false;hideScanOverlay()}}
function initGraph(data){graphData=data;window.__CODEMAPPER_GRAPH__=data;computeNodeDegrees(graphData);currentZoomTransform=d3.zoomIdentity;selectedNodeId=null;currentFocusedClusterKey=null;currentSearchQuery="";$("search-input").value="";loadedNodeCount=graphData.nodes.length>PROGRESSIVE_THRESHOLD?Math.min(PROGRESSIVE_BATCH_SIZE,graphData.nodes.length):graphData.nodes.length;initializeCollapsedClusters();renderGraph(graphData);hideEmptyState();setGraphMetrics(graphData.nodes.length,graphData.edges.length);setMode("Explore");setSelectedLabel("None");clearBlastRadius();startProgressiveLoading();syncActionButtons()}
function updateGraph(data){initGraph(data)}
document.addEventListener("DOMContentLoaded",()=>{applyTheme(localStorage.getItem(THEME_STORAGE_KEY)||"dark",false);window.__CODEWEAVE_SCAN_TARGET__=currentScanTarget;loadSplitRatio();setViewMode(localStorage.getItem(VIEW_MODE_STORAGE_KEY)||"split",false);loadScanHistory();renderScanHistory();showEmptyState();loadLanguageOptions();$("language-input")?.addEventListener("change",(event)=>{currentLanguage=event.target.value||"python"});$("scan-btn").addEventListener("click",scanProject);$("view-split-btn").addEventListener("click",()=>setViewMode("split"));$("view-graph-btn").addEventListener("click",()=>setViewMode("graph"));$("view-panel-btn").addEventListener("click",()=>setViewMode("panel"));$("scan-history-clear-btn").addEventListener("click",clearScanHistory);$("tree-layout-btn").addEventListener("click",()=>setLayoutMode("tree"));$("force-layout-btn").addEventListener("click",()=>setLayoutMode("force"));$("cluster-toggle-btn").addEventListener("click",()=>setClusterMode(!clusterMode));$("theme-toggle-btn").addEventListener("click",()=>{applyTheme(themeMode==="dark"?"light":"dark");if(graphData){renderGraph(graphData);restoreVisualState()}if(window.monaco)window.monaco.editor.setTheme(getMonacoTheme())});$("search-input").addEventListener("input",(event)=>searchNodes(event.target.value));$("clear-blast-btn").addEventListener("click",clearBlastRadius);$("graph-load-more-btn").addEventListener("click",loadMoreNodes);$("graph-show-all-btn").addEventListener("click",showAllNodes);$("export-svg-btn").addEventListener("click",exportGraphSvg);$("export-png-btn").addEventListener("click",exportGraphPng);$("export-json-btn").addEventListener("click",exportGraphJson);$("pane-divider").addEventListener("mousedown",(event)=>{if(window.innerWidth<=980)return;if(viewMode!=="split")setViewMode("split");setDividerDragging(true);event.preventDefault()});$("simulate-blast-btn").addEventListener("click",()=>{const node=getSelectedNode();if(node)triggerBlastRadius(node);else setStatus("Select a node first to simulate blast radius.")});$("view-source-btn").addEventListener("click",()=>{const node=getSelectedNode();if(node)openMonacoModal(node.source_code||"# No source code available");else setStatus("Select a node first to view source.")});$("modal-close-btn").addEventListener("click",()=>{$("monaco-modal").classList.remove("visible")});window.addEventListener("resize",()=>{hideNodeTooltip();if(window.innerWidth>980&&viewMode==="split")applySplitRatio();if(graphData)scheduleGraphResize();monacoEditor?.layout()});window.addEventListener("mousemove",(event)=>{if(!isDraggingDivider||window.innerWidth<=980)return;setSplitRatioFromPointer(event.clientX)});window.addEventListener("mouseup",()=>{if(isDraggingDivider){setDividerDragging(false);scheduleGraphResize()}});syncActionButtons()});
window.initGraph=initGraph;window.updateGraph=updateGraph;window.highlightNode=highlightNode;window.triggerBlastRadius=triggerBlastRadius;window.clearBlastRadius=clearBlastRadius;window.searchNodes=searchNodes;window.openMonacoModal=openMonacoModal;window.loadCachedScanTarget=loadCachedScanTarget;
